const topics=['Összes','MÁV','Magyar közlekedés','Nemzetközi vasút','Jégkorong','Csillagászat','Belpolitika','Külpolitika','Gazdaság'];
const icon={'MÁV':'✦','Magyar közlekedés':'↗','Nemzetközi vasút':'⇄','Jégkorong':'✳','Csillagászat':'☾','Belpolitika':'◈','Külpolitika':'◎','Gazdaság':'↗'};
let articles=[],selected='Összes',limit=13,term='',lastFocus=null;
const el=id=>document.getElementById(id);
const norm=s=>(s||'').toLocaleLowerCase('hu-HU');
function fmtDate(iso){const d=new Date(iso);if(isNaN(d.getTime()))return 'Időpont nem ismert';return new Intl.DateTimeFormat('hu-HU',{year:'numeric',month:'long',day:'numeric',hour:'2-digit',minute:'2-digit',hourCycle:'h23',timeZone:'Europe/Budapest'}).format(d)}
function node(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
function visual(item){const box=node('div','visual fallback');box.dataset.kind=item.category||'';const symbol=node('span','glyph',icon[item.category]||'✳');box.append(symbol);if(item.image&&/^https:\/\//i.test(item.image)){const img=new Image();img.loading='lazy';img.referrerPolicy='no-referrer';img.alt='';img.onload=()=>{box.classList.remove('fallback');symbol.remove()};img.onerror=()=>img.remove();img.src=item.image;box.append(img)}return box}
function openArticle(item){lastFocus=document.activeElement;el('readerCategory').textContent=item.category||'Hír';el('readerTitle').textContent=item.title;el('readerMeta').textContent=[item.source||'Forrás nem ismert',fmtDate(item.published)].join(' · ');el('readerImage').replaceChildren(visual(item));el('readerSummary').textContent=item.summary||'Ehhez a hírhez a forrás nem adott rövid leírást. A teljes cikk az eredeti forrásnál olvasható.';const link=el('readerLink');link.href=/^https?:\/\//i.test(item.url||'')?item.url:'#';el('reader').hidden=false;document.body.classList.add('reader-open');el('readerClose').focus()}
function closeArticle(){el('reader').hidden=true;document.body.classList.remove('reader-open');if(lastFocus?.isConnected)lastFocus.focus()}
function card(item,large=false){const button=node('button',large?'feature':'card');button.type='button';button.setAttribute('aria-label',item.title+' — hír megnyitása itt');button.style.width='100%';button.style.padding='0';button.style.textAlign='left';button.style.color='inherit';button.style.cursor='pointer';button.onclick=()=>openArticle(item);button.append(visual(item));const body=node('div','copy');body.append(node('span','tag',(item.category||'Hír').toLocaleUpperCase('hu-HU')),node('h3','',item.title));if(large&&item.summary)body.append(node('p','summary',item.summary));const info=node('div','source');info.append(node('span','',item.source||'Ismeretlen forrás'),node('span','date',fmtDate(item.published)));body.append(info);button.append(body);return button}
function draw(){const tabs=el('topics');tabs.replaceChildren();topics.forEach(t=>{const b=node('button','chip'+(t===selected?' active':''),t);b.type='button';b.setAttribute('aria-pressed',t===selected?'true':'false');b.onclick=()=>{selected=t;limit=13;draw()};tabs.append(b)});const filtered=articles.filter(x=>(selected==='Összes'||x.category===selected)&&norm(x.title+' '+x.summary+' '+x.source).includes(norm(term)));el('heading').textContent=selected==='Összes'?'Legfrissebb hírek':selected;el('shown').textContent=filtered.length+' HÍR';el('featured').replaceChildren();el('grid').replaceChildren();filtered.slice(0,limit).forEach((x,i)=>(i===0?el('featured'):el('grid')).append(card(x,i===0)));el('empty').hidden=filtered.length>0;el('more').hidden=filtered.length<=limit}
el('search').addEventListener('input',e=>{term=e.target.value;limit=13;draw()});el('more').onclick=()=>{limit+=12;draw()};el('readerClose').onclick=closeArticle;el('readerBackdrop').onclick=closeArticle;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!el('reader').hidden)closeArticle()});
if(localStorage.getItem('horizont-theme')==='dark')document.body.classList.add('dark');el('theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('horizont-theme',document.body.classList.contains('dark')?'dark':'light')};
fetch('./data/news.json?cache='+Date.now(),{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Hírlista nem elérhető');return r.json()}).then(data=>{articles=Array.isArray(data.articles)?data.articles.filter(a=>a.url&&a.title):[];articles.sort((a,b)=>new Date(b.published)-new Date(a.published));el('updated').textContent=data.updated?'Utolsó frissítés: '+fmtDate(data.updated):'Még nem történt automatikus frissítés';el('count').textContent=articles.length+' cikk a gyűjteményben';draw()}).catch(()=>{el('updated').textContent='A hírek betöltése sikertelen';draw()});
